kind: ConfigMap
apiVersion: v1
metadata:
  name: nginx-config
  namespace: nginx-ingress
data:
    opentracing: "True"
    opentracing-tracer: "/usr/local/lib/libjaegertracing_plugin.so"
    opentracing-tracer-config: |
         {
             "service_name": "nginx-ingress",
             "propagation_format": "w3c",
             "sampler": {
                 "type": "const",
                 "param": 1
             },
             "reporter": {
                 "localAgentHostPort": "jaeger.monitoring.svc.cluster.local:6831"
             }
          }
