apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: reviews
spec:
  host: reviews.example.com
  upstreams:
  - name: reviews-v1
    service: reviews-v1
    port: 9080
  - name: reviews-v2-1 
    service: reviews-v2-1
    port: 9080
  routes:
  - path: /
    splits:
    - weight: 1
      action:
        pass: reviews-v1
    - weight: 99
      action:
        pass: reviews-v2-1
 
