apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: bookinfo-vs
spec:
  host: bookinfo.example.com
  tls:
    secret: bookinfo-secret
  upstreams:
  - name: backend
    service: productpage
    port: 9080
  routes:
  - path: /
    action:
      pass: backend
    errorPages:
    - codes: [502]
      redirect:
        code: 301
        url: https://cdn.f5.com/maintenance/f5.com/SorryPage.html
  policies:
  - name: nic-rate-limit-policy